version: '2.1'
services:
  database:
    # build: ./postgres
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: predictiveparking
      POSTGRES_DB: predictiveparking

  elasticsearch:
    image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch5
    command: elasticsearch  -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1 -Epath.repo=/tmp
    ports:
      - "9200:9200"
      - "9300:9300"
    #volumes:
    #  - /home/stephan/elk_okt:/tmp/backup
    #  - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    links:
      - database:database
      - elasticsearch:elasticsearch
    build: ./logstash
    environment:
      START_DATE:
      END_DATE:

  ppapi:
    build: ./api
    ports:
      - "8080:8080"
    links:
      - database:database
      - elasticsearch:elasticsearch
    environment:
      DATABASE_NAME: predictiveparking
      DATABASE_PASSWORD: insecure
      UWSGI_HTTP: ":8080"
      UWSGI_MODULE: "predictive_parking.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"
      UWSGI_PROCESSES: 4
      UWSGI_VACUUM: 1
      UWSGI_HARAKIRI: 15
      UWSGI_DIE_ON_TERM: 1

  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    command: kibana

  customviewer:
    build: ./angular
    ports:
      - "5602:80"
    links:
      - ppapi:ppapi

  csvimporter:
    build: ./csvimporter/
    links:
      - database:database
    environment:
      DATABASE_NAME: predictiveparking
      DATABASE_PASSWORD: insecure
    volumes:
      - ./unzipped:/app/unzipped

  angular:
    build: ./angular
    ports:
      - "8099:80"

  # geoserver with elastic support
  #
  #geoserver:
  #  ports:
  #    - "8080:8080"
  #  links:
  #    - database:database
  #    - elasticsearch:elasticsearch
  #  image: eeacms/elasticgeo
  #

