# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metingen', '0002_auto_20171026_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='geometrie_rd',
        ),
        migrations.RemoveField(
            model_name='scanraw',
            name='geometrie_rd',
        ),
        migrations.AddField(
            model_name='scan',
            name='gps_plate',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='scan',
            name='gps_scandevice',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='scan',
            name='gps_vehicle',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='location_parking_bay',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='parkingbay_angle',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='parkingbay_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='reliability_ANPR',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='reliability_gps',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='scanraw',
            name='gps_plate',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='scanraw',
            name='gps_scandevice',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='scanraw',
            name='gps_vehicle',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='scanraw',
            name='location_parking_bay',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='scanraw',
            name='parkingbay_angle',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scanraw',
            name='parkingbay_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scanraw',
            name='reliability_ANPR',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scanraw',
            name='reliability_gps',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='scanraw',
            name='nha_nr',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
