# Generated by Django 2.1.1 on 2019-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metingen', '0005_auto_20190225_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanraw',
            name='id',
            field=models.CharField(max_length=38, primary_key=True, serialize=False),
        ),
    ]
