# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
