# Generated by Django 2.1.7 on 2019-07-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metingen', '0006_auto_20190225_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_id',
            field=models.IntegerField(unique=True),
        ),
    ]
