# Generated by Django 2.1.7 on 2019-07-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metingen', '0006_auto_20190225_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='device_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
