version: '3.0'
services:

  elasticsearch:
    image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch5
    command: elasticsearch -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1 -Epath.repo=/tmp
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - ./backups/elasticsearch:/tmp/backups

  logstash:
    image: build.datapunt.amsterdam.nl:5000/datapunt/predictive_parking_logstash:${ENVIRONMENT}
    # build: ../logstash
    volumes:
      - data-volume:/app/data
    environment:
      TABLE:

volumes:
  data-volume:

networks:
  default:
    external:
      name: pp_predictiveparking
