version: '3.0'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres:latest
    # build: ../postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: predictiveparking
      POSTGRES_DB: predictiveparking
    networks:
      predictiveparking:
    volumes:
      - databasevolume:/tmp
      - data-volume:/app/data

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/predictive_parking:${ENVIRONMENT}
    # build: ../api/
    links:
      - database:database
      #- elasticsearch:elasticsearch
    environment:
      DATABASE_NAME: predictiveparking
      DATABASE_USER: predictiveparking
      DATABASE_PASSWORD: insecure
      PARKEERVAKKEN_OBJECTSTORE_PASSWORD:
      PGPASSWORD: insecure
      TESTING:
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
    networks:
      predictiveparking:
    volumes:
      - data-volume:/app/data
      - unzip-volume:/app/unzipped

  csvimporter:
    image: build.datapunt.amsterdam.nl:5000/datapunt/predictive_parking_csvpgvoer:${ENVIRONMENT}
    # build: ../csvimporter/
    networks:
      predictiveparking:
    environment:
      DATABASE_NAME: predictiveparking
      DATABASE_PASSWORD: insecure
      TESTING:
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
    volumes:
      - unzip-volume:/app/unzipped

  # backup ALL
  db-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    # build: ../postgres
    networks:
      predictiveparking:
    environment:
      PGPASSWORD: insecure
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo database:5432:predictiveparking:predictiveparking:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump --clean \
                          -Fc \
                          -t wegdelen* \
                          -t mvp \
                          -t metingen* \
                          -t scans* \
                          -t django_migrations  \
                          -T auth*    \
                          -U predictiveparking \
                          -h database -p 5432 \
                          predictiveparking > /tmp/backups/database.dump"

  # incemental
  db-backup-scans:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    # build: ../postgres
    networks:
      predictiveparking:
    environment:
      PGPASSWORD: insecure
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo database:5432:predictiveparking:predictiveparking:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump -t scans* \
                          -Fc \
                          -U predictiveparking \
                          -h database -p 5432 \
                          predictiveparking > /tmp/backups/scans.dump \
              && pg_dump -t wegdelen* \
                          -U predictiveparking \
                          -h database -p 5432 \
                          predictiveparking > /tmp/backups/wegdelen.dump"


volumes:
  data-volume:
  unzip-volume:
  databasevolume:

networks:
  predictiveparking:
