version: '2.1'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: predictiveparking
      POSTGRES_DB: predictiveparking
    volumes:
      - databasevolume:/tmp

  # sudo sysctl -w vm.max_map_count=262144
  # if elasticsearch docker does not start..
  elasticsearch:
    image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch5
    command: elasticsearch -Enetwork.host=_site_ -Ebootstrap.memory_lock=true
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    user: root
    volumes:
      - ./backups/elasticsearch:/tmp/backups
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 5g
    cap_add:
      - IPC_LOCK

  logstash:
    image: build.datapunt.amsterdam.nl:5000/datapunt/predictive_parking_logstash:${ENVIRONMENT}
    #build: ../logstash
    links:
      - database:database
      - elasticsearch:elasticsearch
    environment:
      START_DATE:
      END_DATE:

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/predictive_parking:${ENVIRONMENT}
    # build: ../web/
    links:
      - database:database
      - elasticsearch:elasticsearch
    environment:
      DATABASE_NAME: predictiveparking
      DATABASE_USER: predictiveparking
      DATABASE_PASSWORD: insecure
      PARKEERVAKKEN_OBJECTSTORE_PASSWORD:
      PGPASSWORD: insecure
    user: root
    volumes:
      - data-volume:/app/data
      - unzip-volume:/app/unzipped

  csvimporter:
    image: build.datapunt.amsterdam.nl:5000/datapunt/predictive_parking_csvpgvoer:${ENVIRONMENT}
    # build: ../csvimporter/
    links:
      - database:database
    environment:
      DATABASE_NAME: predictiveparking
      DATABASE_PASSWORD: insecure
    volumes:
      - unzip-volume:/tmp/unzipped

  db-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    links:
      - database
    environment:
      PGPASSWORD: insecure
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo database:5432:predictiveparking:predictiveparking:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump --clean \
                          -Fc \
                          -t scans* \
                          -t django_migrations  \
                          -T auth*    \
                          -U predictiveparking \
                          -h database -p 5432 \
                          predictiveparking > /tmp/backups/database.dump"

  el-backup:
    image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./backups/elasticsearch:/tmp/backups
    user: root
    command: >
      bash -c "curl -X PUT http://elasticsearch:9200/_snapshot/backup -d '{ \"type\": \"fs\", \"settings\": { \"location\": \"/tmp/backups\" }}' \
              && curl -X PUT http://elasticsearch:9200/_snapshot/backup/scans?wait_for_completion=true -d '{ \"indices\": \"scan*\" }' \
              && chown -R 997:997 /tmp/backups"

volumes:
  data-volume:
  unzip-volume:
  databasevolume:
