version: '3.0'
services:
  database:
    image: amsterdam/postgres:latest
    # build: ../postgres
    #ports:
    #  - "5434:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: predictiveparking
      POSTGRES_DB: predictiveparking
    networks:
      predictiveparking:
    volumes:
      - databasevolume:/tmp
      - ./backups:/backups
      - data-volume:/app/data
      - ./backup-db-scans.sh:/backup-db-scans.sh
      - ./backup-db-occupancy.sh:/backup-db-occupancy.sh
    extra_hosts:
      admin.datapunt.amsterdam.nl: 10.99.157.24

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/predictive_parking:${ENVIRONMENT}
    # build: ../api/
    links:
      - database:database
      #- elasticsearch:elasticsearch
    environment:
      DATABASE_NAME: predictiveparking
      DATABASE_USER: predictiveparking
      DATABASE_PASSWORD: insecure
      PARKEERVAKKEN_OBJECTSTORE_PASSWORD: ${PARKEERVAKKEN_OBJECTSTORE_PASSWORD}
      PGPASSWORD: insecure
      STARTDATE:
      ENDDATE:
      TESTING:
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
    user: root
    networks:
      predictiveparking:
    volumes:
      - data-volume:/app/data
      - unzip-volume:/app/unzipped

  csvimporter:
    image: build.datapunt.amsterdam.nl:5000/datapunt/predictive_parking_csvpgvoer:${ENVIRONMENT}
    # build: ../csvimporter/
    networks:
      predictiveparking:
    environment:
      DATABASE_NAME: predictiveparking
      DATABASE_PASSWORD: insecure
      TESTING:
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
    volumes:
      - unzip-volume:/app/unzipped

volumes:
  data-volume:
  unzip-volume:
  databasevolume:

networks:
  predictiveparking:
