# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 08:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buurt',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=4)),
                ('naam', models.CharField(max_length=40)),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('vakken', models.IntegerField(null=True)),
                ('fiscale_vakken', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parkeervak',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('straatnaam', models.CharField(db_index=True, max_length=300)),
                ('soort', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('aantal', models.IntegerField()),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('bgt_wegdeel', models.CharField(db_index=True, max_length=38, null=True)),
                ('bgt_wegdeel_functie', models.CharField(db_index=True, max_length=25, null=True)),
                ('buurt', models.CharField(db_index=True, max_length=4, null=True)),
                ('scan_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WegDeel',
            fields=[
                ('id', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('bgt_functie', models.CharField(max_length=25)),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('vakken', models.IntegerField(null=True)),
                ('fiscale_vakken', models.IntegerField(null=True)),
                ('scan_count', models.IntegerField(null=True)),
            ],
        ),
    ]
