# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0002_selection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='qualcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='sperscode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
