# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0004_roadoccupancy_wegdeel'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadoccupancy',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadoccupancy',
            name='max_occupancy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadoccupancy',
            name='min_occupancy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadoccupancy',
            name='std_occupancy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadoccupancy',
            name='unique_scans',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
