# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 14:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuurtOccupancy',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=4)),
                ('naam', models.CharField(max_length=40)),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('vakken', models.IntegerField(null=True)),
                ('fiscale_vakken', models.IntegerField(null=True)),
                ('occupancy', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadOccupancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bgt_id', models.CharField(db_index=True, max_length=38)),
                ('occupancy', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.IntegerField(db_index=True)),
                ('day2', models.IntegerField(db_index=True, null=True)),
                ('hour1', models.IntegerField(db_index=True)),
                ('hour2', models.IntegerField(db_index=True, null=True)),
                ('month1', models.IntegerField(db_index=True)),
                ('month2', models.IntegerField(db_index=True, null=True)),
                ('year1', models.IntegerField()),
                ('year2', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='roadoccupancy',
            name='selection',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='occupancy.Selection'),
        ),
        migrations.AddField(
            model_name='buurtoccupancy',
            name='selection',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='occupancy.Selection'),
        ),
        migrations.AlterUniqueTogether(
            name='roadoccupancy',
            unique_together=set([('bgt_id', 'selection')]),
        ),
    ]
