# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegdelen', '0001_initial'),
        ('occupancy', '0003_auto_20171019_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadoccupancy',
            name='wegdeel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wegdelen.WegDeel'),
        ),
    ]
