# Generated by Django 2.0.1 on 2018-02-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupancy', '0005_auto_20171120_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='week1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='week2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='month1',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
